---
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - ruby-head

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

bundler_args:
  --jobs 3 --retry 3
